### ISSUE TITLE
Debug IDs in Rolldown

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/javascript-debug-ids#36]
https://github.com/rolldown/rolldown

**Comment by timfish** [comment]
- https://github.com/rolldown/rolldown/pull/2516

**Comment by timfish** [comment]
The PR has been merged. 

I will close this issue with a PR when know the release version as this detail can be added to the `@debugids/rolldown` package.

**Comment by timfish** [comment]
Rolldown includes debug ID support in v0.14.0
